# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin
  admin_email: admin@ideaburn.com
  admin_password: 12345678
  domain_name: ideaburn.com
  cloudinary_name: golden-owl-clound
  cloudinary_api_key: 173569679173764
  cloudinary_api_secret: UKYxGJiBJBu0dwoeO5m8aKMRB7M
  secret_key_base: 9198436f9ef8e60254241e90dbec33643f8265f55255ba880589df44c128913dadae98a7a34766af9d33f3424f01663f31619b2e9af33ef51bc5608f44026fbb

test:
  admin_name: Admin
  admin_email: admin@ideaburn.com
  admin_password: 12345678
  domain_name: ideaburn.com
  cloudinary_name: golden-owl-clound
  cloudinary_api_key: 173569679173764
  cloudinary_api_secret: UKYxGJiBJBu0dwoeO5m8aKMRB7M
  secret_key_base: 9198436f9ef8e60254241e90dbec33643f8265f55255ba880589df44c128913dadae98a7a34766af9d33f3424f01663f31619b2e9af33ef51bc5608f44026fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Admin
  admin_email: admin@ideaburn.com
  admin_password: 12345678
  domain_name: ideaburn.com
  cloudinary_name: <%= ENV["CLOUDINARY_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
